spring:
  config:
    activate:
      on-profile: hub-api
  application:
    name: hub-product-stock-company-api

hub:
  api:
    events:
      enabled: true
  outbox:
    scheduler:
      enabled: true
  route:
    events:
      enabled: true
    planning:
      scheduler:
        enabled: false
    worker:
      enabled: false
    refresh:
      enabled: false
    build:
      scheduler:
        enabled: false

stock:
  events:
    enabled: true
  inbox:
    scheduler:
      enabled: true
